version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2.0.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2-node
    steps:
      - checkout
      - ruby/install-deps
      - run: npm install
  test:
    docker:
      - image: cimg/ruby:2.7.2-node
    steps:
      - checkout
      - ruby/install-deps
      - run: gem install nokogiri ferrum
      - run: sudo apt update
      - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: sudo apt install ./google-chrome-stable_current_amd64.deb
      - run: yarn install
      - run: yarn test

workflows:
  version: 2
  build:
    jobs:
      - build
  test:
    jobs:
      - test