version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2.0.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2-node
      - image: cimg/node:12.22
    steps:
      - checkout
      - ruby/install-deps
      - run: npm install
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7.2-node
      - image: cimg/node:12.22
    steps:
      - checkout
      - ruby/install-deps
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - build
  test:
    jobs:
      - test