#	Last Edit: 2021-03-25
#	Author: Elias Mawa
#
# MAKE TARGETS
# ------------
# the following targets are available :
#	$ make					Build and run all jobs
#	$ make build			Build all jobs script
#	$ make run				Run all jobs
#	$ make full				Run the full sync job
#	$ make partial			Run the partial sync job

all: 
	# TODO

build:
	# TODO

run:
	# TODO

full:
	# TODO

partial:
	# TODO
