#	Last Edit: 2021-03-25
#	Author: Elias Mawa
#
# MAKE TARGETS
# ------------
# the following targets are available :
#	$ make					Build and run
#	$ make build			Build the job script
#	$ make run				Run the job script

all: 
	# TODO

build:
	# TODO

run:
	# TODO